// <auto-generated />
using System;
using CommunicationsApi.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunicationsApi.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20220722134729_InitiaMigrtion01")]
    partial class InitiaMigrtion01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommunicationsApi.Models.MessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FromWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MessageDeletedStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageDeliveredStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageReadStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageRecievedStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageSavedStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("MessageSentStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToWho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageModel");
                });
#pragma warning restore 612, 618
        }
    }
}
